language: ruby

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

rvm:
  - 2.3.8
  - 2.4.8
  - 2.5.7
  - 2.6.5
  - 2.7.0

bundler_args: --jobs=3 --retry=3

install:
  - bundle install --retry=3

cache: bundler

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
